"""
    Simulando o formulario.html, que envia os dados
    via POST para formulario_pythonwebscraping1.php
    Este gera erro por não ter o User Agent definido
"""
import requests

params = {'nome':'Evaldo', 'email':'evaldowolkers@gmail.com',
          'celular':'(28)99948-3074'}
r = requests.post('http://www.pythonparatodos.com.br/'
                  'formulario_pythonwebscraping1.php', data=params)
print(r.text)

"""
Resultado:
<head><title>Not Acceptable!</title></head><body><h1>Not Acceptable!</h1><p>
An appropriate representation of the requested resource could not be found on this server.
This error was generated by Mod_Security.</p></body></html>
"""